spring:
  mvc:
    view:
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/SnowDome
    username: root
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
